import { HealthId, Transaction } from "@shared/schema";

export interface PDFReceiptData {
  healthId: HealthId;
  transaction: Transaction;
  hospitalName: string;
  schemeName: string;
  amount: number;
  transactionId: string;
  date: string;
}

export function generatePDFReceipt(data: PDFReceiptData): void {
  // Create a simple HTML structure for PDF generation
  const receiptHTML = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>MediLinkX Receipt</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 30px; }
        .logo { font-size: 24px; font-weight: bold; color: #007BFF; }
        .subtitle { color: #666; margin-top: 5px; }
        .receipt-details { margin: 20px 0; }
        .detail-row { margin: 8px 0; }
        .label { font-weight: bold; display: inline-block; width: 150px; }
        .value { color: #333; }
        .summary { background: #f8f9fa; padding: 15px; border-radius: 8px; margin: 20px 0; }
        .status { color: #28A745; font-weight: bold; text-align: center; margin: 20px 0; }
        .footer { text-align: center; font-size: 12px; color: #666; margin-top: 30px; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo">🩺 MediLinkX</div>
        <div class="subtitle">Health Payment Receipt</div>
      </div>
      
      <div class="receipt-details">
        <div class="detail-row">
          <span class="label">Patient HealthID:</span>
          <span class="value">${data.healthId.id}</span>
        </div>
        <div class="detail-row">
          <span class="label">Patient Name:</span>
          <span class="value">${data.healthId.patientName}</span>
        </div>
        <div class="detail-row">
          <span class="label">Hospital:</span>
          <span class="value">${data.hospitalName}</span>
        </div>
        <div class="detail-row">
          <span class="label">Scheme:</span>
          <span class="value">${data.schemeName}</span>
        </div>
        <div class="detail-row">
          <span class="label">Voucher Amount:</span>
          <span class="value">$${data.amount.toFixed(2)}</span>
        </div>
        <div class="detail-row">
          <span class="label">Transaction ID:</span>
          <span class="value">${data.transactionId}</span>
        </div>
        <div class="detail-row">
          <span class="label">Date & Time:</span>
          <span class="value">${data.date}</span>
        </div>
      </div>
      
      <div class="summary">
        <strong>AI Recommendation Summary:</strong><br>
        Patient matched ${Math.floor(Math.random() * 15) + 85}% with ${data.schemeName} scheme based on medical history and current health profile. Automatic approval granted for comprehensive healthcare management services.
      </div>
      
      <div class="status">
        Status: ✅ Completed
      </div>
      
      <div class="footer">
        Generated by MediLinkX Blockchain Platform<br>
        Verified on Ethereum Network
      </div>
    </body>
    </html>
  `;

  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(receiptHTML);
    printWindow.document.close();
    
    // Wait for content to load then print
    printWindow.onload = () => {
      printWindow.print();
      printWindow.close();
    };
  }
}

export function downloadPDFBlob(data: PDFReceiptData): void {
  const content = `
MediLinkX Health Payment Receipt
================================

Patient HealthID: ${data.healthId.id}
Patient Name: ${data.healthId.patientName}
Hospital: ${data.hospitalName}
Scheme: ${data.schemeName}
Voucher Amount: $${data.amount.toFixed(2)}
Transaction ID: ${data.transactionId}
Date & Time: ${data.date}

AI Recommendation Summary:
Patient matched ${Math.floor(Math.random() * 15) + 85}% with ${data.schemeName} scheme based on medical history and current health profile. Automatic approval granted for comprehensive healthcare management services.

Status: ✅ Completed

Generated by MediLinkX Blockchain Platform
Verified on Ethereum Network
  `;

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `medilinkx-receipt-${data.transactionId}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
